# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 621)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frequencySweepGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.frequencySweepGroupBox.setObjectName("frequencySweepGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frequencySweepGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frequencySweepGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frequencySweepGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frequencySweepGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frequencySweepGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.frequencySweepGroupBox)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_3.addWidget(self.doubleSpinBox_8, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frequencySweepGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frequencySweepGroupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.viewSettingsGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.viewSettingsGroupBox.setObjectName("viewSettingsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.viewSettingsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridGroupBox = QtWidgets.QGroupBox(self.viewSettingsGroupBox)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_4.setContentsMargins(-1, 1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.gridGroupBox)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_4.addWidget(self.doubleSpinBox_3, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.gridGroupBox)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.doubleSpinBox_4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox)
        self.gridGroupBox_2 = QtWidgets.QGroupBox(self.viewSettingsGroupBox)
        self.gridGroupBox_2.setObjectName("gridGroupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridGroupBox_2)
        self.gridLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.gridGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.gridGroupBox_2)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_5.addWidget(self.doubleSpinBox_5, 0, 1, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.gridGroupBox_2)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_5.addWidget(self.doubleSpinBox_6, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox_2)
        self.pushButton = QtWidgets.QPushButton(self.viewSettingsGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.viewSettingsGroupBox, 1, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidget_2.setWindowTitle("")
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.freqSlider = QtWidgets.QSlider(self.dockWidgetContents_2)
        self.freqSlider.setMinimum(1)
        self.freqSlider.setMaximum(10000)
        self.freqSlider.setSingleStep(100)
        self.freqSlider.setPageStep(500)
        self.freqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.freqSlider.setObjectName("freqSlider")
        self.gridLayout_6.addWidget(self.freqSlider, 0, 1, 1, 1)
        self.freqSpinBox = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_2)
        self.freqSpinBox.setObjectName("freqSpinBox")
        self.gridLayout_6.addWidget(self.freqSpinBox, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_FEM_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_FEM_File.setObjectName("actionLoad_FEM_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoad_FEM_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.frequencySweepGroupBox.setTitle(_translate("MainWindow", "Frequency sweep"))
        self.label_2.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Steps"))
        self.viewSettingsGroupBox.setTitle(_translate("MainWindow", "View Settings"))
        self.gridGroupBox.setTitle(_translate("MainWindow", "X-Axis Range"))
        self.label_3.setText(_translate("MainWindow", "min"))
        self.label_4.setText(_translate("MainWindow", "max"))
        self.gridGroupBox_2.setTitle(_translate("MainWindow", "Y-Axis Range"))
        self.label_5.setText(_translate("MainWindow", "min"))
        self.label_6.setText(_translate("MainWindow", "max"))
        self.pushButton.setText(_translate("MainWindow", "Auto"))
        self.actionLoad_FEM_File.setText(_translate("MainWindow", "Load FEM File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

